# Generated by Django 5.0.7 on 2024-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablemodel',
            name='type',
            field=models.CharField(choices=[('NOTE', 'Nota'), ('FOLDER', 'Pasta')], default=''),
            preserve_default=False,
        ),
    ]
