# Generated by Django 5.0.7 on 2024-09-04 11:18

import django.db.models.deletion
import folders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('folders', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('shareablemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.shareablemodel')),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(default=folders.models.Folders.get_default_id, on_delete=django.db.models.deletion.PROTECT, to='folders.folders')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='tags.tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.shareablemodel', models.Model),
        ),
    ]
