# Generated by Django 5.0.7 on 2024-08-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('notes', '0002_note_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='folders.folders'),
            preserve_default=False,
        ),
    ]
