# Generated by Django 5.0.7 on 2024-10-19 14:21

import django.db.models.deletion
import folders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('notes', '0003_alter_note_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(default=folders.models.Folders.get_default_id, on_delete=django.db.models.deletion.CASCADE, to='folders.folders'),
        ),
    ]
